React + vite project template
RadekBucki/ADoTO-Frontend pull request #2
Opened 2023-03-29 11:09 UTC by Ryszawy

2023-03-29 12:05 UTC, RadekBucki requested changes

2023-03-29 12:05 UTC, RadekBucki commented on public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
This comment is probably left over from another repository? 😉

2023-03-29 12:06 UTC, RadekBucki commented
Please also pin the issue to PR 😉

2023-03-30 18:45 UTC, Damian2057 approved these changes

2023-04-01 08:28 UTC, merged